#!/usr/bin/perl
#
# Script to show us how close we are to that 140 hour mark :)
#


use warnings;
use strict;

local %_ = ();

for(@ARGV) {
    open my $fh, "<$_" or die "Couldn't open $_ for reading";
    local @_ = <$fh>;
    close $fh;
    my $good = 0;
    my $name;
    for(@_) {
        if(/^#summary Log for (.*?)\s*$/) {
            $good = 1;
            $name = $1;
            last;
        }
    }
    next unless $good;
    $_{$name} = 0;
    for(@_) {
        $_{$name} += ($3 - $1) + ($4 - $2) / 60
            if /^\d+\/\d+\/\d+\s+(\d+):(\d+)-(\d+):(\d+)/;
    }
    close $fh;
}

print "#summary How close are we to the magic mark?\n#labels log\n\n";
printf("|| [Log%s %s] || %.02f ||\n", first_name($_), $_, $_{$_})
    for sort {last_name($a) cmp last_name($b)} keys %_;
printf("\n_Page autogenerated %s._\n", scalar localtime);

sub first_name {
    shift =~ /^(\S+)/;
    return $1;
}

sub last_name {
    shift =~ /(\S+)$/;
    return $1;
}
